# Generated by Django 6.0.5 on 2026-09-01 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=120, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Action', help_text='Comma-separated genres, e.g. Action, Sci-Fi', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(default=100, help_text='Popularity / Votes count'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AddField(
            model_name='theater',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=3),
        ),
    ]
