# Generated by Django 6.0.5 on 2026-09-01 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_booking_booking_id_booking_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
