# Generated by Django 6.0.5 on 2026-09-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_castmember_genre_language_movie_age_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
    ]
